name: Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  repository_dispatch:
    types: [update-cv]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install Python poetry 
        uses: abatilo/actions-poetry@v2.2.0
        with:
          poetry-version: 1.3.1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Pull latest CV
        run: |
          git clone https://sharadmv:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/sharadmv/cv.git

      - name: Compile CV
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: cv
          root_file: resume.tex

      - name: Install Python dependencies
        run: |
          poetry install

      - name: Build blog posts
        run: |
          mkdir -p public/notebooks/
          poetry run python scripts/build_notebooks.py notebooks/ public/notebooks/

      - name: Build website
        run: |
          npm install
          npm run build

      - name: Copy CV
        run: |
          mkdir -p build/pdf
          cp cv/resume.pdf build/pdf/cv-sharadvikram.pdf


      - name: Copy files to the s3 bucket
        run: |
          aws s3 sync build/ s3://sharadvikram.com/
