name: Deploy

on:
  push:
    branches: [ s3 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Python poetry 
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Install Python dependencies
        run: |
          poetry install

      - name: Build blog posts
        run: |
          mkdir -p public/notebooks/
          poetry run scripts/build_notebooks.py notebooks/ public/notebooks/

      - name: Build website
        run: |
          npm install
          npm run build

      - name: Copy files to the s3 bucket
        run: |
          aws s3 sync build/ s3://sharadvikram.com/
